name: PHPUnit tests

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3

        with:
          bootstrap: vendor/autoload.php
          configuration: Test/phpunit.xml
          php_extensions: "xdebug"
          coverage_clover: "coverage/clover.xml"
